project_name: wsgnatsd
release:
  github:
    owner: aricart
    name: wsgnatsd
  name_template: 'v{{.Tag}}'
builds:
  - main: wsnatsd.go
    binary: wsgnatsd
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS

