project_name: wsgnatsd
release:
  github:
    owner: aricart
    name: wsgnatsd
  name_template: 'v{{.Tag}}'
builds:
  - main: wsnatsd.go
    binary: wsgnatsd
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  wrap_in_directory: true
  name_template: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: zip

checksum:
  name_template: '{{ .ProjectName }}-v{{ .Version }}-checksums.txt'

snapshot:
  name_template: 'dev'