project_name: wsgnatsd
release:
  github:
    owner: aricart
    name: wsgnatsd
  name_template: '{{.Tag}}'
builds:
  - main: main.go
    binary: wsgnatsd
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

dist: build

archive:
  wrap_in_directory: false
  name_template: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: zip

checksum:
  name_template: '{{ .ProjectName }}-v{{ .Version }}-checksums.txt'

snapshot:
  name_template: 'dev'

brews:
  - name: wsgnatsd
    folder: Formula
    github:
      owner: aricart
      name: wsgnatsd
    url_template: "https://github.com/aricart/wsgnatsd/releases/download/{{ .Tag }}/wsgnatsd-darwin-amd64.zip"
    homepage: "https://github.com/aricart/wsgnatsd"
    description: "A websocket server proxy for nats-server"
    skip_upload: false
    test: |
      system "#{bin}/wsgnatsd --help"
    install: |
      bin.install "program"